# define loggable files via regex (0 = not loggable, 1 = loggable)
map $uri $loggable {
  default                                   1;
  ~^/(?:favicon|apple-touch-icon)           0;
  /robots.txt                               0;
}
