# status codes 1xx, 2xx, 3xx are info, 4xx is warn, 5xx is error
map $status $log_level {
  ~^1       "INFO";
  ~^2       "INFO";
  ~^3       "INFO";
  ~^4       "WARN";
  ~^5       "ERROR";
  default   "INFO";
}
