# ~* has higher precedence than /,
# access to resources requires therefore try_files

upstream php  {
  # docker container
  server wordpress:9000;
}

# define loggable files via regex (0 = not loggable, 1 = loggable)
map $uri $loggable {
    default                                   1;
    ~^/(?:favicon|apple-touch-icon)           0;
    /robots.txt                               0;
}

server {
  listen [::]:80 ipv6only=on;
  listen 0.0.0.0:80;

  charset utf-8;
  access_log /var/log/nginx/access.log main if=$loggable;
  error_log  /var/log/nginx/error.log warn;

  server_name _;
  index index.php;
  root /var/www/html;

  # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
  sendfile off;

  # Disable ETag Header
  # etag off;

  # Allow only specific HTTP methods
  # if ($request_method !~ ^(GET|HEAD|POST|PUT|DELETE)$) {
  #    return 405;
  # }

  include /etc/nginx/conf.d/config/forbidden.conf;
  include /etc/nginx/conf.d/config/w3tc.conf;

  # Cache for static assets
  location ~* \.(css|js|ico)$ {
    expires max;
    log_not_found off;
  }

  # prevent image hotlinking, except for provided domains
  # use this only when you dont have a CDN
  # change domain to your own
  # check: curl -I --referer http://comes-from.example.com http://localhost/wp-content/uploads/2025/04/image.jpg
  location ~* \.(jpe?g|png|webp|gif)$ {
    # valid_referers none blocked localhost *.localhost;
    # if ($invalid_referer) {
    #   return 403;
    # }

    # Apply caching if referer is valid
    expires max;
    log_not_found off;
  }

  location / {
    # try_files $uri $uri/ /index.php$is_args$args;

    # W3 TOTAL CACHE use cached or actual file if they exists, otherwise pass request to WordPress
    # FOR Normal WordPress (without Multisite)
    try_files /wp-content/w3tc/pgcache/$cache_uri/_index.html $uri $uri/ /index.php?$args ;
  }

  location ~ \.php$ {
    fastcgi_pass php;
    fastcgi_index index.php;
    try_files $uri =404;
    # regex to split $uri to $fastcgi_script_name and $fastcgi_path_info
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    set $path_info $fastcgi_path_info;

    # default fastcgi_params
    include fastcgi_params;

    # fastcgi params
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    # for symlink cache issue (If you update your symlink for the current to a new release, your application will still be point to the older release.)
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
  }
}
