volumes:
  db_data:
    name: ${PROJECT_NAME}-dbdata
networks:
  default:
    name: ${PROJECT_NAME}-network
    driver: bridge

services:
  ########################
  # Webserver & WordPress
  ########################
  wordpress:
    container_name: ${PROJECT_NAME}-wordpress
    image: ${PROJECT_NAME}/wordpress:0.0.1
    hostname: ${PROJECT_NAME}-wordpress
    # dont change user, root required to init wordpress
    # user: ${UID:-1000}
    # working_dir: /var/www/html
    restart: unless-stopped
    build:
      context: ./.docker/service/wordpress
      target: develop
      args:
        UID: ${UID}
        GID: ${GID}
        PASS: ${PASS}
        TZ: ${TZ}
        WP_VERSION: ${WP_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    init: true
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-dev:/home/${UNAME}/wp-dev
      ## enable when needed locally
      # - ./.docker/data/logs/nginx:/var/log/nginx:r
    env_file:
      - .docker/service/wordpress/.wordpress.env
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}-db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      # for symlink.sh, absolute paths only
      DEV_DIR: /home/$UNAME/wp-dev
      WORDPRESS_DIR: /var/www/html
    ports:
      - "127.0.0.1:${WORDPRESS_PORT_HOST:-80}:80"
    depends_on:
      db:
        condition: service_healthy

  wpcli:
    container_name: ${PROJECT_NAME}-wpcli
    image: ${PROJECT_NAME}/wpcli:0.0.1
    user: ${UNAME}
    build:
      context: ./.docker/service/wpcli
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
        PASS: ${PASS}
        TZ: ${TZ}
        PHP_VERSION: ${PHP_VERSION}
    init: true
    # make curl localhost possible inside this container
    network_mode: "service:wordpress"
    env_file:
      - .docker/service/wordpress/.wordpress.env
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}-db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      # for setup-wordpress.sh
      WORDPRESS_PORT_HOST: ${WORDPRESS_PORT_HOST:-80}
    # mirrors filesystem of the listed services
    volumes_from:
      - wordpress
    depends_on:
      db:
        condition: service_healthy

  ########################
  # Database
  ########################
  db:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:${MARIADB_VERSION}
    user: mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      # MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./.docker/service/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  ########################
  # Database UI
  ########################
  adminer:
    container_name: ${PROJECT_NAME}-adminer
    image: adminer:latest
    user: adminer
    restart: unless-stopped
    environment:
      # https://github.com/vrana/adminer/tree/master/plugins
      # listing plugins here will move them from /plugins to /plugins-enabled
      ADMINER_PLUGINS: "tables-filter edit-calendar edit-textarea"
      # https://github.com/vrana/adminer/tree/master/designs
      # ADMINER_DESIGN: "nicu"
      # default server entry in the login form
      # ADMINER_DEFAULT_SERVER: "db"
      ADMINER_SERVERS_JSON: '[{"server":"db:3306","username":"${DB_USER}","password":"${DB_PASS}","db":"${DB_NAME}","label":"Local Dev WordPress"}]'
    ports:
      - "127.0.0.1:${ADMINER_PORT_HOST:-8080}:8080" # web ui
    volumes:
      - ./.docker/service/adminer/plugins/autologin.php:/var/www/html/plugins/autologin.php
      - ./.docker/service/adminer/plugins-enabled/autologin.php:/var/www/html/plugins-enabled/autologin.php

  ########################
  # Email Catcher
  #######################
  mailpit:
    container_name: ${PROJECT_NAME}-mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    expose:
      - 1025 # smtp server
    ports:
      - "127.0.0.1:${MAILPIT_PORT_HOST:-8025}:8025" # web ui
    environment:
      TZ: ${TZ}
