log_format main_json escape=json '{'
  '"timestamp": "$time_iso8601",'
  '"level":"$log_level",'
  '"pid": "$pid",'
  '"client_ip": "$remote_addr",'
  '"request_id": "$request_id",'
  '"http_method": "$request_method",'
  '"http_path": "$uri",'
  '"protocol": "$server_protocol",'
  '"host": "$host",'
  '"user_agent": "$http_user_agent",'
  '"referer": "$http_referer",'
  '"status_code": $status,'
  '"bytes_sent": $body_bytes_sent,'
  '"request_time_secs": $request_time'
'}';
