# ~* has higher precedence than /,
# access to resources requires therefore try_files

upstream php  {
  # docker container
  # server wordpress:9000;
  server localhost:9000;
}

# define loggable files via regex (0 = not loggable, 1 = loggable)
map $uri $loggable {
    default                                   1;
    ~^/(?:favicon|apple-touch-icon)           0;
    /robots.txt                               0;
}

include /etc/nginx/conf.d/config/blacklist.conf;

server {
  listen [::]:80 ipv6only=on;
  listen 0.0.0.0:80;

  charset utf-8;

  access_log /var/log/nginx/access.log main if=$loggable;
  access_log /dev/stdout main if=$loggable;

  error_log  /var/log/nginx/error.log warn;
  error_log  /dev/stderr warn;

  server_name _;
  index index.php;
  root /var/www/html;

  # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
  sendfile off;

  # Disable ETag Header
  # etag off;

  # Allow only specific HTTP methods
  # if ($request_method !~ ^(GET|HEAD|POST|PUT|DELETE)$) {
  #    return 405;
  # }

  # requires blacklist.conf
  if ($bad_referer) {
    return 444;
  }

  # Allow fpm ping and status from localhost
  # location ~ ^/(fpm-status|fpm-ping)$ {
  #   access_log off;
  #   allow 127.0.0.1;
  #   deny all;
  #   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  #   include fastcgi_params;
  #   fastcgi_pass unix:/run/php-fpm.sock;
  # }

  include /etc/nginx/conf.d/config/forbidden.conf;

  # Cache for static assets
  location ~* \.(css|js|ico)$ {
    expires max;
    log_not_found off;
  }

  # prevent image hotlinking, except for provided domains
  # use this only when you dont have a CDN
  # change domains in valid_referers to your own after "blocked" keyword
  # check: curl -I --referer http://comes-from.example.com http://localhost/wp-content/uploads/2025/04/image.jpg
  location ~* \.(jpe?g|png|webp|gif)$ {
    valid_referers none blocked localhost *.localhost;
    if ($invalid_referer) {return 403;}

    # Apply caching if referer is valid
    expires max;
    log_not_found off;
  }

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~ \.php$ {
    fastcgi_pass php;
    fastcgi_index index.php;
    try_files $uri =404;
    # regex to split $uri to $fastcgi_script_name and $fastcgi_path_info
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    set $path_info $fastcgi_path_info;

    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

    # default fastcgi_params
    include fastcgi_params;

    # fastcgi params settings (used by supervisor)
    fastcgi_buffer_size 128k;
    fastcgi_buffers 4 256k;
    fastcgi_busy_buffers_size 256k;

    fastcgi_connect_timeout 60;
    fastcgi_read_timeout 300;

    # fastcgi params
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    # for symlink cache issue (If you update your symlink for the current to a new release, your application will still be point to the older release.)
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
  }
}
