;; Resource Limits
;; memory_limit = -1
memory_limit = 256M
max_input_vars = 4000
max_execution_time = 180
client_max_body_size =  128M

;; file Uploads and post size
upload_max_filesize = 64M
post_max_size = 64M

;; uploads
file_uploads = On

date.timezone = Europe/Berlin
display_errors = On
error_reporting = E_ALL
;; production: disable error reports which are not an immediate issue
; error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED

;; Hide X-Powered-By header
expose_php = off
