[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
socketfile=/var/run/supervisord.sock
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor

[unix_http_server]
file=/var/run/supervisord.sock
chmod=0700
## anyone who can access that socket file (at /var/run/supervisord.sock) has full control over the processes managed by Supervisor without needing a password. Add protection in production.
# username=admin    ; Add this
# password=password ; Add this (use a real secret in production)

[supervisorctl]
serverurl=unix:///var/run/supervisord.sock ; use a unix:// URL for a unix socket
# username=admin    ; Must match above
# password=password ; Must match above

# bridge between the Supervisor daemon and the CLI
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/*.conf
